name: Build Flutter for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Klonowanie repozytorium z GitLab
        run: |
          if (Test-Path tomos) { Remove-Item tomos -Recurse -Force }
          git clone https://gitlab.com/gnejusz_pompejusz/tomos.git tomos
        shell: pwsh

      - name: Instalacja Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pobieranie zależności Flutter
        working-directory: tomos
        run: flutter pub get

      - name: Włączanie wsparcia dla Windows desktop
        working-directory: tomos
        run: flutter config --enable-windows-desktop

      - name: Kompilacja aplikacji dla Windows
        working-directory: tomos
        run: |
          flutter clean
          flutter build windows --release

      - name: Przesyłanie artefaktu
        uses: actions/upload-artifact@v4
        with:
          name: tomos-windows
          path: tomos\build\windows\runner\Release\
