name: Build Flutter for Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    steps:
      - name: Klonowanie repozytorium z GitLab
        run: |
          git clone https://gitlab.com/gnejusz_pompejusz/tomos.git tomos

      - name: Pobieranie zależności Flutter
        working-directory: tomos
        run: flutter pub get

      - name: Włączanie wsparcia dla Linux desktop
        working-directory: tomos
        run: flutter config --enable-linux-desktop

      - name: Kompilacja aplikacji dla Linux
        working-directory: tomos
        run: |
          flutter clean
          flutter build linux --release

      - name: Przesyłanie artefaktu
        uses: actions/upload-artifact@v4
        with:
          name: tomos-linux
          path: tomos/build/linux/release/bundle/
